# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alex Gaw's ACA Blog
email: alexanderjgaw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'll use this blog to talk about things I'm learning, working on,
  or struggling with while I make my way through the Austin Coding
  Academy dev courses. Oh yeah.
baseurl: "/aca-blog" # the subpath of your site, e.g. /blog
url: "http://alexjgaw.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  alexjgaw

# Build settings
markdown: kramdown
